apiVersion: v1
kind: ConfigMap
metadata:
  name: mstr-mysqlinitcmap
data:
  initdb.sql: |-
    CREATE TABLE aadhaar ( name varchar(255) NOT NULL,
    sex char NOT NULL, birth DATE  NOT NULL, death DATE  NULL,
    id int(255) NOT NULL AUTO_INCREMENT, PRIMARY KEY (id) );
    CREATE USER 'usera'@'%' IDENTIFIED BY 'usera';
    GRANT REPLICATION SLAVE ON *.* TO 'usera' IDENTIFIED BY 'usera';
    FLUSH PRIVILEGES;

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mstr-replcmap
data:
  my.conf: |
    [mysqld]
    log-bin=mysql-bin
    server-id=1
