apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /opt/mysql-slave
    server: 192.168.8.62
  persistentVolumeReclaimPolicy: Recycle
