apiVersion: v1
kind: PersistentVolume
metadata:
  name: ro-slave-nfs-datadir-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /opt/crc-slave/var/lib/mysql
    server: 192.168.8.61
  persistentVolumeReclaimPolicy: Recycle

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ro-slave-nfs-datadir-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: ro-slave-nfs-datadir-pv
