apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /opt/nfs
    server: 192.168.190.144
  persistentVolumeReclaimPolicy: Recycle
