apiVersion: v1
kind: PersistentVolume
metadata:
  name: slave-nfs-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /opt/crc-slave
    server: 192.168.8.61
  persistentVolumeReclaimPolicy: Recycle

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slave-nfs-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: slave-nfs-pv
