apiVersion: v1
kind: Pod
metadata:
  name: spring-mysql-slave
  labels:
    app: spring-mysql-slave
spec:
    containers:
    - name: spring-mysql-ui-slave
      image: index.docker.io/neethirocks/spring-mysql:1.0
      ports:
        - containerPort: 8080
      env:
      - name: spring_jpa_database
        value: mysql
      - name: spring_datasource_url
        value: jdbc:mysql://mysql-slave:3306/test?useSSL=false
      - name: spring_datasource_username
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_USER
      - name: spring_datasource_password
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: spring-mysql-service-slave
  labels:
    name: spring-mysql-service-slave
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
      protocol: TCP
      nodePort: 31001      
  selector:
    app: spring-mysql-slave
  type: NodePort
